version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - ~/.ssh:/home/vscode/.ssh:cached
      - ~/.npmrc:/home/vscode/.npmrc:cached
      - ~/.gitconfig:/home/vscode/.gitconfig:cached
    command: sleep infinity
    working_dir: /workspaces/ts-eslint-boilerplate
